spring:
  application:
    name: auth-service
  profiles:
    active: dev
  datasource:
    # T?rnak isaretleri ozel karakter sorunlarini onleyebilir.
    url: "jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ve Hibernate ayarlari
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # Bu satir Keycloak kullanimi ile ilgili, bizim projemizle mi ilgili?
          # Eger degilse, bu blogu silebilirsiniz.
          issuer-uri: http://keycloak:8080/realms/microservices

# Uygulamaya ozel (custom) ayarlar
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${EXPIRATION_DURATION:PT1H} # Duration formatini kullandiginizdan emin olun

# Sunucu ayarlari
server:
  port: ${PORT:8081}