services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - fintech-network
    depends_on:
      - eureka-server
      - keycloak
      - transaction-service # Tüm servislerin baslamasi beklesin
    environment:
        # Gateway'in calisacagi port
        - SERVER_PORT=8080
        # Eureka Server'in adresi (container network'ü üzerinden servis adiyla)
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
        # Keycloak issuer URI (container network'ü üzerinden servis adiyla)
        - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:9080/realms/fintech-realm

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "8085:8085"
    networks:
      - fintech-network
    depends_on:
        - eureka-server
        - keycloak
        - mysql-db # veritabaninin baslamasini bekle
    environment:
      # Servisin calisacagi port
      - SERVER_PORT=8085
      # Eureka Server'in adresi
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      # Keycloak issuer URI
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:9080/realms/fintech-realm
      # Veritabani baglanti bilgileri (container network'ü üzerinden servis adıyla)
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=fintech # Kendi veritabanı adın
      - MYSQL_USER=root # Kendi kullanıcı adın
      - MYSQL_PASSWORD=1234 # Kendi şifren
      # JWT Secret'a artık ihtiyaç yok!

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
  #      KEYCLOAK_HOSTNAME: keycloak
  #      KEYCLOAK_PROXY_ADDRESS_FORWARDING: true
    ports:
      - "9080:9080"
      - "9000:9000"
    networks:
      - fintech-network

  mysql-db: # 'mysql-db' adında bir MySQL servisi tanımlar
    image: mysql:8.0 # Resmi bir MySQL imajını kullanır
    container_name: mysql-db
    ports:
      - "33061:3306" # Ana makine portu 33061'i konteyner portu 3306'ya eşler (DB'ye dışarıdan erişim için isteğe bağlı)
    environment:
      - MYSQL_ROOT_PASSWORD=cokgizlisifre
      - MYSQL_DATABASE=defaultdb
    volumes:
      - mysql_data:/var/lib/mysql # MySQL verilerini kalıcı hale getirir
    networks:
      - fintech-network
networks:
  fintech-network:
volumes:
  mysql_data: # Veri kalıcılığı için adlandırılmış bir volume tanımlar

