services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  fin-tech:
    build: ./fin-tech
    ports:
      - "8082:8082"
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
  transaction-service:
    build: ./transaction-service
    ports:
      - "8085:8085"

  keycloak:
    image: keycloak/keycloak:25.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_VENDOR: dev-file
      KEYCLOAK_EXTRA_ARGS: --health-enabled=true
  #      KEYCLOAK_HOSTNAME: keycloak
  #      KEYCLOAK_PROXY_ADDRESS_FORWARDING: true
    ports:
      - "9080:9080"
      - "9000:9000"
    depends_on:
      - mysql-db

  mysql-db: # 'mysql-db' adında bir MySQL servisi tanımlar
    image: mysql:8.0 # Resmi bir MySQL imajını kullanır
    ports:
      - "33061:3306" # Ana makine portu 33061'i konteyner portu 3306'ya eşler (DB'ye dışarıdan erişim için isteğe bağlı)
    environment:
      - MYSQL_ROOT_PASSWORD=cokgizlisifre
      - MYSQL_DATABASE=defaultdb
    volumes:
      - mysql_data: /var/lib/mysql # MySQL verilerini kalıcı hale getirir
      - ./init:/docker-entrypoint-initdb.d

  volumes:
    mysql_data: # Veri kalıcılığı için adlandırılmış bir volume tanımlar

