spring:
  application:
    name: transaction-service
  profiles:
    active: dev
  datasource:
    # URL'yi tirnak icine almak, ozel karakterlerden kaynaklanabilecek sorunlari onler.
    url: "jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ve Hibernate ayarlari
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # Eger Keycloak kullanmiyorsaniz bu blogu tamamen silin.
          # Eger kullaniyorsaniz, bu servisin de Keycloak'a ulasmasi gerekir.
          issuer-uri: http://keycloak:8080/realms/microservices

# Uygulamaya ozel (custom) ayarlar
app:
  jwt:
    secret: ${JWT_SECRET} # AUTH-SERVICE ILE AYNI OLMALI!
    expiration: ${EXPIRATION_DURATION:PT1H} # Bu burada cok gerekli degil, token burada uretilmiyor.

# Sunucu ayarlari
server:
  port: ${PORT:8085}