spring:
  application:
    name: transaction-service
  profiles:
    active: dev
  datasource:
    # URL'yi tirnak icine almak, ozel karakterlerden kaynaklanabilecek sorunlari onler.
    url: "jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ve Hibernate ayarlari
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # Eger Keycloak kullanmiyorsaniz bu blogu tamamen silin.
          # Eger kullaniyorsaniz, bu servisin de Keycloak'a ulasmasi gerekir.
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9080/realms/fintech-realm}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
# Sunucu ayarlari
server:
  port: ${PORT:8085}